[browser]
gatherUsageStats = false

[server]
headless = true
enableCORS = false
enableXsrfProtection = true

[theme]
primaryColor = "#003781"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F4F7FB"
textColor = "#1E293B"
font = "sans serif"
